#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -o average-out
#SBATCH -p MEM_128
#SBATCH -J average
ulimit -s unlimited
module load anaconda/5.3.1
source ~/.bashrc
conda activate welldy
date "+Began at: %d %H:%M:%S"
python average.py 
python graph-aver.py
date "+Finished at: %d %H:%M:%S"
