#!/bin/bash
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH -o demo1out
#SBATCH -p MEM_128
#SBATCH -J cnnlstm1
ulimit -s unlimited
source ~/.bashrc
conda activate test1
date "+Began at: %d %H:%M:%S"
python demo1.py 
python predclstm1.py
date "+Finished at: %d %H:%M:%S"

