#!/bin/bash
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH -o demo2out
#SBATCH -p MEM_128
#SBATCH -J cnnlstm2
ulimit -s unlimited
source ~/.bashrc
conda activate test1
date "+Began at: %d %H:%M:%S"
python demo2.py 
python predclstm2.py
date "+Finished at: %d %H:%M:%S"

