#!/bin/bash
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH -o demo3out
#SBATCH -p MEM_128
#SBATCH -J cnndemo3
ulimit -s unlimited
source ~/.bashrc
conda activate test2
date "+Began at: %d %H:%M:%S"
python demo3.py 
python predcnn3.py
date "+Finished at: %d %H:%M:%S"

