#!/bin/bash
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH -o demo1out
#SBATCH -p MEM_128
#SBATCH -J cnndemo1
ulimit -s unlimited
source ~/.bashrc
conda activate test2
date "+Began at: %d %H:%M:%S"
python demo1.py 
python predcnn1.py
date "+Finished at: %d %H:%M:%S"

